---
include:
  # Original eyelash_sofle 
  - board: nice_nano_v2
    shield: eyelash_sofle_central_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DBOARD_ROOT=${ZMKCONFIG_DIR}/.. -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_central_dongle_oled
  - board: nice_nano_v2
    shield: eyelash_sofle_peripheral_left nice_view
  - board: nice_nano_v2
    shield: eyelash_sofle_peripheral_right nice_view
  
  - board: nice_nano_v2
    shield: settings_reset
